use serde::{Deserialize, Serialize};

/// 求職者データの基本構造体（ハローワーク版では未使用だが互換性のため残す）
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JobSeekerRow {
    pub row_type: String,
    pub job_type: String,
    pub prefecture: String,
    pub municipality: String,
    pub label: Option<String>,
    pub value: Option<f64>,
    pub sub_label: Option<String>,
    pub sub_value: Option<f64>,
    pub extra_json: Option<String>,
}

/// 都道府県の順序（JIS 北→南）
pub const PREFECTURE_ORDER: [&str; 47] = [
    "北海道",
    "青森県",
    "岩手県",
    "宮城県",
    "秋田県",
    "山形県",
    "福島県",
    "茨城県",
    "栃木県",
    "群馬県",
    "埼玉県",
    "千葉県",
    "東京都",
    "神奈川県",
    "新潟県",
    "富山県",
    "石川県",
    "福井県",
    "山梨県",
    "長野県",
    "岐阜県",
    "静岡県",
    "愛知県",
    "三重県",
    "滋賀県",
    "京都府",
    "大阪府",
    "兵庫県",
    "奈良県",
    "和歌山県",
    "鳥取県",
    "島根県",
    "岡山県",
    "広島県",
    "山口県",
    "徳島県",
    "香川県",
    "愛媛県",
    "高知県",
    "福岡県",
    "佐賀県",
    "長崎県",
    "熊本県",
    "大分県",
    "宮崎県",
    "鹿児島県",
    "沖縄県",
];

/// 産業大分類（13種）
pub const JOB_TYPES: [&str; 13] = [
    "老人福祉・介護",
    "医療",
    "建設業",
    "製造業",
    "小売業",
    "飲食業",
    "サービス業",
    "IT・通信",
    "派遣・人材",
    "運輸業",
    "教育・保育",
    "宿泊業",
    "その他",
];

/// 産業分類の表示名（UIで使用）
pub const INDUSTRY_LABELS: [(&str, &str); 13] = [
    ("老人福祉・介護", "老人福祉・介護"),
    ("医療", "医療"),
    ("建設業", "建設業"),
    ("製造業", "製造業"),
    ("小売業", "小売業"),
    ("飲食業", "飲食業"),
    ("サービス業", "サービス業"),
    ("IT・通信", "IT・通信"),
    ("派遣・人材", "派遣・人材"),
    ("運輸業", "運輸業"),
    ("教育・保育", "教育・保育"),
    ("宿泊業", "宿泊業"),
    ("その他", "その他"),
];
